# Generated by Django 5.0 on 2025-12-27 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Manufacturer name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for manufacturer', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this manufacturer is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'db_table': 'manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Part category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the part category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Part Category',
                'verbose_name_plural': 'Part Categories',
                'db_table': 'part_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Model name (e.g., CL, Accord)', max_length=100)),
                ('code', models.CharField(help_text='Short code for model', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(help_text='Associated manufacturer', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='authentication.manufacturer')),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
                'db_table': 'vehicle_models',
                'ordering': ['name'],
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PartsInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Vehicle year')),
                ('name', models.CharField(help_text="Customer's name", max_length=255)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=255)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('zipcode', models.CharField(help_text="Customer's ZIP code", max_length=10)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information or special requests')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('quoted', 'Quote Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', help_text='Current status of the inquiry', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('manufacturer', models.ForeignKey(help_text='Vehicle manufacturer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='authentication.manufacturer')),
                ('part_category', models.ForeignKey(help_text='Part category being searched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='authentication.partcategory')),
                ('model', models.ForeignKey(help_text='Vehicle model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='authentication.vehiclemodel')),
            ],
            options={
                'verbose_name': 'Parts Inquiry',
                'verbose_name_plural': 'Parts Inquiries',
                'db_table': 'parts_inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='parts_inqui_email_98c269_idx'), models.Index(fields=['status'], name='parts_inqui_status_5f4483_idx'), models.Index(fields=['-created_at'], name='parts_inqui_created_c48ca0_idx'), models.Index(fields=['manufacturer', 'model'], name='parts_inqui_manufac_86792a_idx')],
            },
        ),
    ]
