# Generated by Django 4.2.11 on 2025-12-31 12:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_manufacturer_partcategory_vehiclemodel_partsinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartImageGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Vehicle Year')),
                ('part_name', models.CharField(help_text='Specific part name (e.g., Front Bumper, Headlight Left)', max_length=255)),
                ('part_number', models.CharField(blank=True, help_text='OEM or manufacturer part number (optional)', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the part', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Make this part gallery visible in API')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this part in listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_image_galleries', to='authentication.manufacturer', verbose_name='Manufacturer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_image_galleries', to='authentication.vehiclemodel', verbose_name='Vehicle Model')),
                ('part_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_image_galleries', to='authentication.partcategory', verbose_name='Part Category')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_part_galleries', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Part Image Gallery',
                'verbose_name_plural': 'Part Image Galleries',
                'db_table': 'part_image_galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('part_name', models.CharField(help_text='Specific part name', max_length=255)),
                ('part_number', models.CharField(blank=True, help_text='OEM/Manufacturer part number', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='parts/images/%Y/%m/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for showing discounts', max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert when stock falls below this number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued'), ('coming_soon', 'Coming Soon')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('oem', 'OEM'), ('aftermarket', 'Aftermarket')], default='used', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs', max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H', max_length=100, null=True)),
                ('warranty_months', models.IntegerField(blank=True, help_text='Warranty period in months', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gallery_reference', models.ForeignKey(blank=True, help_text='Link to reference image gallery for this part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='authentication.partimagegallery')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.manufacturer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vehiclemodel')),
                ('part_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.partcategory')),
            ],
            options={
                'verbose_name': 'Part Inventory',
                'verbose_name_plural': 'Parts Inventory',
                'db_table': 'part_inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Upload part image (will be stored in R2)', upload_to='part_gallery_images/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True, help_text='R2 public URL (auto-filled after upload)', max_length=500, null=True)),
                ('r2_key', models.CharField(blank=True, help_text='R2 storage key/path', max_length=500, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption or description', max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/thumbnail image')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying images (lower = first)')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='authentication.partimagegallery', verbose_name='Part Gallery')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Part Image Upload',
                'verbose_name_plural': 'Part Image Uploads',
                'db_table': 'part_image_uploads',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PartImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('galleries', models.ManyToManyField(blank=True, related_name='tags', to='authentication.partimagegallery')),
            ],
            options={
                'verbose_name': 'Image Tag',
                'verbose_name_plural': 'Image Tags',
                'db_table': 'part_image_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parts/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='authentication.partinventory')),
            ],
            options={
                'verbose_name': 'Part Image',
                'verbose_name_plural': 'Part Images',
                'db_table': 'part_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partinventory',
            index=models.Index(fields=['year', 'manufacturer', 'model'], name='part_invent_year_a932f7_idx'),
        ),
        migrations.AddIndex(
            model_name='partinventory',
            index=models.Index(fields=['part_category'], name='part_invent_part_ca_27e946_idx'),
        ),
        migrations.AddIndex(
            model_name='partinventory',
            index=models.Index(fields=['status'], name='part_invent_status_c9c80a_idx'),
        ),
        migrations.AddIndex(
            model_name='partimageupload',
            index=models.Index(fields=['gallery', 'is_primary'], name='part_image__gallery_7ef6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='partimageupload',
            index=models.Index(fields=['display_order'], name='part_image__display_a77c18_idx'),
        ),
        migrations.AddIndex(
            model_name='partimagegallery',
            index=models.Index(fields=['year', 'manufacturer', 'model'], name='part_image__year_d142a6_idx'),
        ),
        migrations.AddIndex(
            model_name='partimagegallery',
            index=models.Index(fields=['part_category'], name='part_image__part_ca_30563e_idx'),
        ),
        migrations.AddIndex(
            model_name='partimagegallery',
            index=models.Index(fields=['is_published'], name='part_image__is_publ_495c02_idx'),
        ),
    ]
