# Generated by Django 4.2.11 on 2025-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_partimagegallery_partinventory_partimageupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partimagegallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
