# Generated by Django 4.2.11 on 2026-01-19 15:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_alter_partimagegallery_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('campaign', models.CharField(default='default', max_length=255)),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'email_link_clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='PartPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Vehicle Year')),
                ('part_name', models.CharField(help_text='Specific part name', max_length=255)),
                ('part_number', models.CharField(blank=True, help_text='OEM or manufacturer part number (optional)', max_length=100, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used_excellent', 'Used - Excellent'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair'), ('refurbished', 'Refurbished'), ('oem', 'OEM'), ('aftermarket', 'Aftermarket')], default='used_good', help_text='Condition of the part', max_length=20)),
                ('price_type', models.CharField(choices=[('retail', 'Retail Price'), ('wholesale', 'Wholesale Price'), ('core_charge', 'Core Charge'), ('exchange', 'Exchange Price')], default='retail', help_text='Type of pricing', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original/MSRP price (for showing discounts)', max_digits=10, null=True)),
                ('core_charge', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Core charge if applicable', max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Estimated shipping cost', max_digits=10, null=True)),
                ('in_stock', models.BooleanField(default=True, help_text='Whether this part is currently in stock')),
                ('quantity_available', models.IntegerField(default=1, help_text='Number of units available', validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField(default=django.utils.timezone.now, help_text='Price valid from this date')),
                ('valid_until', models.DateField(blank=True, help_text='Price valid until this date (optional)', null=True)),
                ('warranty_months', models.IntegerField(blank=True, help_text='Warranty period in months', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this price/part')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this price is currently active/visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this price in listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part Price',
                'verbose_name_plural': 'Part Prices',
                'db_table': 'part_prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'db_table': 'shipping_addresses',
            },
        ),
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('destination_url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tracked_links',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='partsinquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='partsinquiry',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='partsinquiry',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='partsinquiry',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='partsinquiry',
            name='email_error',
            field=models.TextField(blank=True, help_text='Error message if email failed to send'),
        ),
        migrations.AddField(
            model_name='partsinquiry',
            name='email_message',
            field=models.TextField(blank=True, help_text='Custom message sent in the email'),
        ),
        migrations.AddField(
            model_name='partsinquiry',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether a reply email has been sent'),
        ),
        migrations.AddField(
            model_name='partsinquiry',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the reply email was sent', null=True),
        ),
        migrations.AddField(
            model_name='partsinquiry',
            name='email_sent_by',
            field=models.ForeignKey(blank=True, help_text='Admin who sent the email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_inquiry_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partsinquiry',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Subject line of the sent email', max_length=255),
        ),
        migrations.AddField(
            model_name='partsinquiry',
            name='parts_info_sent',
            field=models.JSONField(blank=True, help_text='Information about parts sent in the email', null=True),
        ),
        migrations.AddField(
            model_name='partsinquiry',
            name='parts_needed',
            field=models.TextField(blank=True, default='', help_text='Description of parts needed'),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='email',
            field=models.EmailField(help_text='Customer email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Car manufacturer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.manufacturer'),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='model',
            field=models.ForeignKey(blank=True, help_text='Car model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='name',
            field=models.CharField(help_text='Customer name', max_length=255),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='part_category',
            field=models.ForeignKey(blank=True, help_text='Category of parts needed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.partcategory'),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='phone',
            field=models.CharField(blank=True, help_text='Customer phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='year',
            field=models.IntegerField(blank=True, default=2024, help_text='Car year', null=True),
        ),
        migrations.AlterField(
            model_name='partsinquiry',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Customer zipcode', max_length=10),
        ),
        migrations.AddIndex(
            model_name='partsinquiry',
            index=models.Index(fields=['email_sent'], name='parts_inqui_email_s_182d7c_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prices', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='partprice',
            name='gallery_reference',
            field=models.ForeignKey(blank=True, help_text='Link to image gallery for this part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='authentication.partimagegallery'),
        ),
        migrations.AddField(
            model_name='partprice',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Link to inventory item if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='authentication.partinventory'),
        ),
        migrations.AddField(
            model_name='partprice',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_prices', to='authentication.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='partprice',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_prices', to='authentication.vehiclemodel', verbose_name='Vehicle Model'),
        ),
        migrations.AddField(
            model_name='partprice',
            name='part_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_prices', to='authentication.partcategory', verbose_name='Part Category'),
        ),
        migrations.AddIndex(
            model_name='emaillinkclick',
            index=models.Index(fields=['link_id', 'user_id'], name='email_link__link_id_a80a96_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillinkclick',
            index=models.Index(fields=['campaign'], name='email_link__campaig_60f114_idx'),
        ),
        migrations.AddIndex(
            model_name='partprice',
            index=models.Index(fields=['year', 'manufacturer', 'model'], name='part_prices_year_864bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='partprice',
            index=models.Index(fields=['part_category'], name='part_prices_part_ca_017bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='partprice',
            index=models.Index(fields=['is_active', 'in_stock'], name='part_prices_is_acti_b8f28a_idx'),
        ),
        migrations.AddIndex(
            model_name='partprice',
            index=models.Index(fields=['condition', 'price_type'], name='part_prices_conditi_2606bf_idx'),
        ),
    ]
