# authentication/management/commands/populate_sample_data.py
# Create this file in: authentication/management/commands/populate_sample_data.py

from django.core.management.base import BaseCommand
from authentication.models import Manufacturer, VehicleModel, PartCategory


class Command(BaseCommand):
    help = "Populate database with sample manufacturers, models, and part categories"

    def handle(self, *args, **kwargs):
        self.stdout.write("Creating sample data...")

        # Create Manufacturers
        manufacturers_data = [
        {"name": "Acura", "code": "ACURA" },
        {"name": "Alfa Romeo", "code": "ALFA" },
        {"name": "AMC", "code": "AMC" },
        {"name": "Aston Martin", "code": "ASTON" },
        {"name": "Audi", "code": "AUDI" },
        {"name": "Bentley", "code": "BENTLEY" },
        {"name": "BMW", "code": "BMW" },
        {"name": "Bugatti", "code": "BUGATTI" },
        {"name": "Buick", "code": "BUICK" },
        {"name": "Cadillac", "code": "CADILLAC" },
        {"name": "Chevrolet", "code": "CHEVY" },
        {"name": "Chrysler", "code": "CHRYSLER" },
        {"name": "Daewoo", "code": "DAEWOO" },
        {"name": "Daihatsu", "code": "DAIHATSU" },
        {"name": "Datsun", "code": "DATSUN" },
        {"name": "DeLorean", "code": "DELOREAN" },
        {"name": "Dodge", "code": "DODGE" },
        {"name": "Ferrari", "code": "FERRARI" },
        {"name": "Fiat", "code": "FIAT" },
        {"name": "Fisker", "code": "FISKER" },
        {"name": "Ford", "code": "FORD" },
        {"name": "Genesis", "code": "GENESIS" },
        {"name": "Geo", "code": "GEO" },
        {"name": "GMC", "code": "GMC" },
        {"name": "Honda", "code": "HONDA" },
        {"name": "Hummer", "code": "HUMMER" },
        {"name": "Hyundai", "code": "HYUNDAI" },
        {"name": "Infiniti", "code": "INFINITI" },
        {"name": "Isuzu", "code": "ISUZU" },
        {"name": "Jaguar", "code": "JAGUAR" },
        {"name": "Jeep", "code": "JEEP" },
        {"name": "Kia", "code": "KIA" },
        {"name": "Lamborghini", "code": "LAMBO" },
        {"name": "Land Rover", "code": "LANDROVER" },
        {"name": "Lexus", "code": "LEXUS" },
        {"name": "Lincoln", "code": "LINCOLN" },
        {"name": "Lotus", "code": "LOTUS" },
        {"name": "Maserati", "code": "MASERATI" },
        {"name": "Maybach", "code": "MAYBACH" },
        {"name": "Mazda", "code": "MAZDA" },
        {"name": "McLaren", "code": "MCLAREN" },
        {"name": "Mercedes-Benz", "code": "MERC" },
        {"name": "Mercury", "code": "MERCURY" },
        {"name": "Mini", "code": "MINI" },
        {"name": "Mitsubishi", "code": "MITSUBISHI" },
        {"name": "Nissan", "code": "NISSAN" },
        {"name": "Oldsmobile", "code": "OLDS" },
        {"name": "Peugeot", "code": "PEUGEOT" },
        {"name": "Plymouth", "code": "PLYMOUTH" },
        {"name": "Pontiac", "code": "PONTIAC" },
        {"name": "Porsche", "code": "PORSCHE" },
        {"name": "Ram", "code": "RAM" },
        {"name": "Renault", "code": "RENAULT" },
        {"name": "Rolls-Royce", "code": "ROLLSROYCE" },
        {"name": "Saab", "code": "SAAB" },
        {"name": "Saturn", "code": "SATURN" },
        {"name": "Scion", "code": "SCION" },
        {"name": "Smart", "code": "SMART" },
        {"name": "Subaru", "code": "SUBARU" },
        {"name": "Suzuki", "code": "SUZUKI" },
        {"name": "Tesla", "code": "TESLA" },
        {"name": "Toyota", "code": "TOYOTA" },
        {"name": "Volkswagen", "code": "VW" },
        {"name": "Volvo", "code": "VOLVO" }
    ]



        manufacturers = {}
        for mfg_data in manufacturers_data:
            mfg, created = Manufacturer.objects.get_or_create(
                code=mfg_data["code"], defaults={"name": mfg_data["name"]}
            )
            manufacturers[mfg_data["code"]] = mfg
            if created:
                self.stdout.write(f"  Created manufacturer: {mfg.name}")

        # Create Vehicle Models
        models_data = [
            # Acura Models
            {"manufacturer": "ACURA", "name": "CL", "code": "CL"},
            {"manufacturer": "ACURA", "name": "ILX", "code": "ILX"},
            {"manufacturer": "ACURA", "name": "Integra", "code": "INTEGRA"},
            {"manufacturer": "ACURA", "name": "Legend", "code": "LEGEND"},
            {"manufacturer": "ACURA", "name": "MDX", "code": "MDX"},
            {"manufacturer": "ACURA", "name": "NSX", "code": "NSX"},
            {"manufacturer": "ACURA", "name": "RDX", "code": "RDX"},
            {"manufacturer": "ACURA", "name": "RL", "code": "RL"},
            {"manufacturer": "ACURA", "name": "RLX", "code": "RLX"},
            {"manufacturer": "ACURA", "name": "RSX", "code": "RSX"},
            {"manufacturer": "ACURA", "name": "SLX", "code": "SLX"},
            {"manufacturer": "ACURA", "name": "TL", "code": "TL"},
            {"manufacturer": "ACURA", "name": "TLX", "code": "TLX"},
            {"manufacturer": "ACURA", "name": "TSX", "code": "TSX"},
            {"manufacturer": "ACURA", "name": "Vigor", "code": "VIGOR"},
            {"manufacturer": "ACURA", "name": "ZDX", "code": "ZDX"},

            # Alfa Romeo Models
            {"manufacturer": "ALFA", "name": "4C", "code": "4C"},
            {"manufacturer": "ALFA", "name": "Giulia", "code": "GIULIA"},
            {"manufacturer": "ALFA", "name": "Stelvio", "code": "STELVIO"},
            {"manufacturer": "ALFA", "name": "Spider", "code": "SPIDER"},

            # AMC Models
            {"manufacturer": "AMC", "name": "Concord", "code": "CONCORD"},
            {"manufacturer": "AMC", "name": "Eagle", "code": "EAGLE"},
            {"manufacturer": "AMC", "name": "Spirit", "code": "SPIRIT"},

            ##Aston Martin Models
            {"manufacturer": "ASTON", "name": "DB11", "code": "DB11"},
            {"manufacturer": "ASTON", "name": "DB9", "code": "DB9"},
            {"manufacturer": "ASTON", "name": "DBS", "code": "DBS"},
            {"manufacturer": "ASTON", "name": "DBX", "code": "DBX"},
            {"manufacturer": "ASTON", "name": "Rapide", "code": "RAPIDE"},
            {"manufacturer": "ASTON", "name": "Vanquish", "code": "VANQUISH"},
            {"manufacturer": "ASTON", "name": "Vantage", "code": "VANTAGE"},

            # Audi Models
            {"manufacturer": "AUDI", "name": "A3", "code": "A3"},
            {"manufacturer": "AUDI", "name": "A4", "code": "A4"},
            {"manufacturer": "AUDI", "name": "A5", "code": "A5"},
            {"manufacturer": "AUDI", "name": "A6", "code": "A6"},
            {"manufacturer": "AUDI", "name": "A7", "code": "A7"},
            {"manufacturer": "AUDI", "name": "A8", "code": "A8"},
            {"manufacturer": "AUDI", "name": "Allroad", "code": "ALLROAD"},
            {"manufacturer": "AUDI", "name": "e-tron", "code": "ETRON"},
            {"manufacturer": "AUDI", "name": "Q3", "code": "Q3"},
            {"manufacturer": "AUDI", "name": "Q5", "code": "Q5"},
            {"manufacturer": "AUDI", "name": "Q7", "code": "Q7"},
            {"manufacturer": "AUDI", "name": "Q8", "code": "Q8"},
            {"manufacturer": "AUDI", "name": "R8", "code": "R8"},
            {"manufacturer": "AUDI", "name": "RS3", "code": "RS3"},
            {"manufacturer": "AUDI", "name": "RS5", "code": "RS5"},
            {"manufacturer": "AUDI", "name": "RS7", "code": "RS7"},
            {"manufacturer": "AUDI", "name": "S3", "code": "S3"},
            {"manufacturer": "AUDI", "name": "S4", "code": "S4"},
            {"manufacturer": "AUDI", "name": "S5", "code": "S5"},
            {"manufacturer": "AUDI", "name": "S6", "code": "S6"},
            {"manufacturer": "AUDI", "name": "S7", "code": "S7"},
            {"manufacturer": "AUDI", "name": "S8", "code": "S8"},
            {"manufacturer": "AUDI", "name": "SQ5", "code": "SQ5"},
            {"manufacturer": "AUDI", "name": "TT", "code": "TT"},

            # Bentley Models
            {"manufacturer": "BENTLEY", "name": "Arnage", "code": "ARNAGE"},
            {"manufacturer": "BENTLEY", "name": "Azure", "code": "AZURE"},
            {"manufacturer": "BENTLEY", "name": "Bentayga", "code": "BENTAYGA"},
            {"manufacturer": "BENTLEY", "name": "Brooklands", "code": "BROOKLANDS"},
            {"manufacturer": "BENTLEY", "name": "Continental", "code": "CONTINENTAL"},
            {"manufacturer": "BENTLEY", "name": "Flying Spur", "code": "FLYINGSPUR"},
            {"manufacturer": "BENTLEY", "name": "Mulsanne", "code": "MULSANNE"},

            # BMW Models
            {"manufacturer": "BMW", "name": "1 Series", "code": "1SERIES"},
            {"manufacturer": "BMW", "name": "2 Series", "code": "2SERIES"},
            {"manufacturer": "BMW", "name": "3 Series", "code": "3SERIES"},
            {"manufacturer": "BMW", "name": "4 Series", "code": "4SERIES"},
            {"manufacturer": "BMW", "name": "5 Series", "code": "5SERIES"},
            {"manufacturer": "BMW", "name": "6 Series", "code": "6SERIES"},
            {"manufacturer": "BMW", "name": "7 Series", "code": "7SERIES"},
            {"manufacturer": "BMW", "name": "8 Series", "code": "8SERIES"},
            {"manufacturer": "BMW", "name": "i3", "code": "I3"},
            {"manufacturer": "BMW", "name": "i4", "code": "I4"},
            {"manufacturer": "BMW", "name": "i8", "code": "I8"},
            {"manufacturer": "BMW", "name": "iX", "code": "IX"},
            {"manufacturer": "BMW", "name": "M2", "code": "M2"},
            {"manufacturer": "BMW", "name": "M3", "code": "M3"},
            {"manufacturer": "BMW", "name": "M4", "code": "M4"},
            {"manufacturer": "BMW", "name": "M5", "code": "M5"},
            {"manufacturer": "BMW", "name": "M6", "code": "M6"},
            {"manufacturer": "BMW", "name": "M8", "code": "M8"},
            {"manufacturer": "BMW", "name": "X1", "code": "X1"},
            {"manufacturer": "BMW", "name": "X2", "code": "X2"},
            {"manufacturer": "BMW", "name": "X3", "code": "X3"},
            {"manufacturer": "BMW", "name": "X4", "code": "X4"},
            {"manufacturer": "BMW", "name": "X5", "code": "X5"},
            {"manufacturer": "BMW", "name": "X6", "code": "X6"},
            {"manufacturer": "BMW", "name": "X7", "code": "X7"},
            {"manufacturer": "BMW", "name": "Z3", "code": "Z3"},
            {"manufacturer": "BMW", "name": "Z4", "code": "Z4"},

            # Buick Models
            {"manufacturer": "BUICK", "name": "Century", "code": "CENTURY"},
            {"manufacturer": "BUICK", "name": "Enclave", "code": "ENCLAVE"},
            {"manufacturer": "BUICK", "name": "Encore", "code": "ENCORE"},
            {"manufacturer": "BUICK", "name": "Envision", "code": "ENVISION"},
            {"manufacturer": "BUICK", "name": "LaCrosse", "code": "LACROSSE"},
            {"manufacturer": "BUICK", "name": "LeSabre", "code": "LESABRE"},
            {"manufacturer": "BUICK", "name": "Lucerne", "code": "LUCERNE"},
            {"manufacturer": "BUICK", "name": "Park Avenue", "code": "PARKAVE"},
            {"manufacturer": "BUICK", "name": "Rainier", "code": "RAINIER"},
            {"manufacturer": "BUICK", "name": "Regal", "code": "REGAL"},
            {"manufacturer": "BUICK", "name": "Rendezvous", "code": "RENDEZVOUS"},
            {"manufacturer": "BUICK", "name": "Riviera", "code": "RIVIERA"},
            {"manufacturer": "BUICK", "name": "Roadmaster", "code": "ROADMASTER"},
            {"manufacturer": "BUICK", "name": "Skylark", "code": "SKYLARK"},
            {"manufacturer": "BUICK", "name": "Terraza", "code": "TERRAZA"},
            {"manufacturer": "BUICK", "name": "Verano", "code": "VERANO"},

            #Cadillac Models
            {"manufacturer": "CADILLAC", "name": "ATS", "code": "ATS"},
            {"manufacturer": "CADILLAC", "name": "Allante", "code": "ALLANTE"},
            {"manufacturer": "CADILLAC", "name": "Brougham", "code": "BROUGHAM"},
            {"manufacturer": "CADILLAC", "name": "CT4", "code": "CT4"},
            {"manufacturer": "CADILLAC", "name": "CT5", "code": "CT5"},
            {"manufacturer": "CADILLAC", "name": "CT6", "code": "CT6"},
            {"manufacturer": "CADILLAC", "name": "CTS", "code": "CTS"},
            {"manufacturer": "CADILLAC", "name": "Catera", "code": "CATERA"},
            {"manufacturer": "CADILLAC", "name": "Cimarron", "code": "CIMARRON"},
            {"manufacturer": "CADILLAC", "name": "DeVille", "code": "DEVILLE"},
            {"manufacturer": "CADILLAC", "name": "DTS", "code": "DTS"},
            {"manufacturer": "CADILLAC", "name": "Eldorado", "code": "ELDORADO"},
            {"manufacturer": "CADILLAC", "name": "ELR", "code": "ELR"},
            {"manufacturer": "CADILLAC", "name": "Escalade", "code": "ESCALADE"},
            {"manufacturer": "CADILLAC", "name": "Fleetwood", "code": "FLEETWOOD"},
            {"manufacturer": "CADILLAC", "name": "Seville", "code": "SEVILLE"},
            {"manufacturer": "CADILLAC", "name": "SRX", "code": "SRX"},
            {"manufacturer": "CADILLAC", "name": "STS", "code": "STS"},
            {"manufacturer": "CADILLAC", "name": "XLR", "code": "XLR"},
            {"manufacturer": "CADILLAC", "name": "XT4", "code": "XT4"},
            {"manufacturer": "CADILLAC", "name": "XT5", "code": "XT5"},
            {"manufacturer": "CADILLAC", "name": "XT6", "code": "XT6"},
            {"manufacturer": "CADILLAC", "name": "XTS", "code": "XTS"},

            # Chevrolet Models
            {"manufacturer": "CHEVY", "name": "Astro", "code": "ASTRO"},
            {"manufacturer": "CHEVY", "name": "Avalanche", "code": "AVALANCHE"},
            {"manufacturer": "CHEVY", "name": "Aveo", "code": "AVEO"},
            {"manufacturer": "CHEVY", "name": "Beretta", "code": "BERETTA"},
            {"manufacturer": "CHEVY", "name": "Blazer", "code": "BLAZER"},
            {"manufacturer": "CHEVY", "name": "Bolt", "code": "BOLT"},
            {"manufacturer": "CHEVY", "name": "Camaro", "code": "CAMARO"},
            {"manufacturer": "CHEVY", "name": "Caprice", "code": "CAPRICE"},
            {"manufacturer": "CHEVY", "name": "Captiva", "code": "CAPTIVA"},
            {"manufacturer": "CHEVY", "name": "Cavalier", "code": "CAVALIER"},
            {"manufacturer": "CHEVY", "name": "Celebrity", "code": "CELEBRITY"},
            {"manufacturer": "CHEVY", "name": "Chevelle", "code": "CHEVELLE"},
            {"manufacturer": "CHEVY", "name": "Citation", "code": "CITATION"},
            {"manufacturer": "CHEVY", "name": "Cobalt", "code": "COBALT"},
            {"manufacturer": "CHEVY", "name": "Colorado", "code": "COLORADO"},
            {"manufacturer": "CHEVY", "name": "Corsica", "code": "CORSICA"},
            {"manufacturer": "CHEVY", "name": "Corvette", "code": "CORVETTE"},
            {"manufacturer": "CHEVY", "name": "Cruze", "code": "CRUZE"},
            {"manufacturer": "CHEVY", "name": "El Camino", "code": "ELCAMINO"},
            {"manufacturer": "CHEVY", "name": "Equinox", "code": "EQUINOX"},
            {"manufacturer": "CHEVY", "name": "Express", "code": "EXPRESS"},
            {"manufacturer": "CHEVY", "name": "HHR", "code": "HHR"},
            {"manufacturer": "CHEVY", "name": "Impala", "code": "IMPALA"},
            {"manufacturer": "CHEVY", "name": "Lumina", "code": "LUMINA"},
            {"manufacturer": "CHEVY", "name": "Malibu", "code": "MALIBU"},
            {"manufacturer": "CHEVY", "name": "Metro", "code": "METRO"},
            {"manufacturer": "CHEVY", "name": "Monte Carlo", "code": "MONTECARLO"},
            {"manufacturer": "CHEVY", "name": "Nova", "code": "NOVA"},
            {"manufacturer": "CHEVY", "name": "Prizm", "code": "PRIZM"},
            {"manufacturer": "CHEVY", "name": "S-10", "code": "S10"},
            {"manufacturer": "CHEVY", "name": "Silverado", "code": "SILVERADO"},
            {"manufacturer": "CHEVY", "name": "Sonic", "code": "SONIC"},
            {"manufacturer": "CHEVY", "name": "Spark", "code": "SPARK"},
            {"manufacturer": "CHEVY", "name": "Spectrum", "code": "SPECTRUM"},
            {"manufacturer": "CHEVY", "name": "Sprint", "code": "SPRINT"},
            {"manufacturer": "CHEVY", "name": "SS", "code": "SS"},
            {"manufacturer": "CHEVY", "name": "SSR", "code": "SSR"},
            {"manufacturer": "CHEVY", "name": "Suburban", "code": "SUBURBAN"},
            {"manufacturer": "CHEVY", "name": "Tahoe", "code": "TAHOE"},
            {"manufacturer": "CHEVY", "name": "Tracker", "code": "TRACKER"},
            {"manufacturer": "CHEVY", "name": "TrailBlazer", "code": "TRAILBLAZER"},
            {"manufacturer": "CHEVY", "name": "Traverse", "code": "TRAVERSE"},
            {"manufacturer": "CHEVY", "name": "Trax", "code": "TRAX"},
            {"manufacturer": "CHEVY", "name": "Uplander", "code": "UPLANDER"},
            {"manufacturer": "CHEVY", "name": "Venture", "code": "VENTURE"},
            {"manufacturer": "CHEVY", "name": "Volt", "code": "VOLT"},

            # Chrysler Models
            {"manufacturer": "CHRYSLER", "name": "200", "code": "200"},
            {"manufacturer": "CHRYSLER", "name": "300", "code": "300"},
            {"manufacturer": "CHRYSLER", "name": "Aspen", "code": "ASPEN"},
            {"manufacturer": "CHRYSLER", "name": "Cirrus", "code": "CIRRUS"},
            {"manufacturer": "CHRYSLER", "name": "Concorde", "code": "CONCORDE"},
            {"manufacturer": "CHRYSLER", "name": "Conquest", "code": "CONQUEST"},
            {"manufacturer": "CHRYSLER", "name": "Crossfire", "code": "CROSSFIRE"},
            {"manufacturer": "CHRYSLER", "name": "Fifth Avenue", "code": "FIFTHAVE"},
            {"manufacturer": "CHRYSLER", "name": "Grand Voyager", "code": "GRANDVOYAGER"},
            {"manufacturer": "CHRYSLER", "name": "Imperial", "code": "IMPERIAL"},
            {"manufacturer": "CHRYSLER", "name": "Intrepid", "code": "INTREPID"},
            {"manufacturer": "CHRYSLER", "name": "LeBaron", "code": "LEBARON"},
            {"manufacturer": "CHRYSLER", "name": "LHS", "code": "LHS"},
            {"manufacturer": "CHRYSLER", "name": "New Yorker", "code": "NEWYORKER"},
            {"manufacturer": "CHRYSLER", "name": "Pacifica", "code": "PACIFICA"},
            {"manufacturer": "CHRYSLER", "name": "Prowler", "code": "PROWLER"},
            {"manufacturer": "CHRYSLER", "name": "PT Cruiser", "code": "PTCRUISER"},
            {"manufacturer": "CHRYSLER", "name": "Sebring", "code": "SEBRING"},
            {"manufacturer": "CHRYSLER", "name": "TC", "code": "TC"},
            {"manufacturer": "CHRYSLER", "name": "Town & Country", "code": "TOWNCOUNTRY"},
            {"manufacturer": "CHRYSLER", "name": "Voyager", "code": "VOYAGER"},

            #Dodge Models
            {"manufacturer": "DODGE", "name": "Aries", "code": "ARIES"},
            {"manufacturer": "DODGE", "name": "Avenger", "code": "AVENGER"},
            {"manufacturer": "DODGE", "name": "Caliber", "code": "CALIBER"},
            {"manufacturer": "DODGE", "name": "Caravan", "code": "CARAVAN"},
            {"manufacturer": "DODGE", "name": "Challenger", "code": "CHALLENGER"},
            {"manufacturer": "DODGE", "name": "Charger", "code": "CHARGER"},
            {"manufacturer": "DODGE", "name": "Colt", "code": "COLT"},
            {"manufacturer": "DODGE", "name": "Coronet", "code": "CORONET"},
            {"manufacturer": "DODGE", "name": "Dakota", "code": "DAKOTA"},
            {"manufacturer": "DODGE", "name": "Dart", "code": "DART"},
            {"manufacturer": "DODGE", "name": "Daytona", "code": "DAYTONA"},
            {"manufacturer": "DODGE", "name": "Diplomat", "code": "DIPLOMAT"},
            {"manufacturer": "DODGE", "name": "Durango", "code": "DURANGO"},
            {"manufacturer": "DODGE", "name": "Dynasty", "code": "DYNASTY"},
            {"manufacturer": "DODGE", "name": "Grand Caravan", "code": "GRANDCARAVAN"},
            {"manufacturer": "DODGE", "name": "Intrepid", "code": "INTREPID"},
            {"manufacturer": "DODGE", "name": "Journey", "code": "JOURNEY"},
            {"manufacturer": "DODGE", "name": "Lancer", "code": "LANCER"},
            {"manufacturer": "DODGE", "name": "Magnum", "code": "MAGNUM"},
            {"manufacturer": "DODGE", "name": "Mirada", "code": "MIRADA"},
            {"manufacturer": "DODGE", "name": "Monaco", "code": "MONACO"},
            {"manufacturer": "DODGE", "name": "Neon", "code": "NEON"},
            {"manufacturer": "DODGE", "name": "Nitro", "code": "NITRO"},
            {"manufacturer": "DODGE", "name": "Omni", "code": "OMNI"},
            {"manufacturer": "DODGE", "name": "Raider", "code": "RAIDER"},
            {"manufacturer": "DODGE", "name": "Ram", "code": "RAM"},
            {"manufacturer": "DODGE", "name": "Ramcharger", "code": "RAMCHARGER"},
            {"manufacturer": "DODGE", "name": "Rampage", "code": "RAMPAGE"},
            {"manufacturer": "DODGE", "name": "Shadow", "code": "SHADOW"},
            {"manufacturer": "DODGE", "name": "Spirit", "code": "SPIRIT"},
            {"manufacturer": "DODGE", "name": "Stealth", "code": "STEALTH"},
            {"manufacturer": "DODGE", "name": "Stratus", "code": "STRATUS"},
            {"manufacturer": "DODGE", "name": "Viper", "code": "VIPER"},

            #Ferrari Models
            {"manufacturer": "FERRARI", "name": "348", "code": "348"},
            {"manufacturer": "FERRARI", "name": "360", "code": "360"},
            {"manufacturer": "FERRARI", "name": "458", "code": "458"},
            {"manufacturer": "FERRARI", "name": "488", "code": "488"},
            {"manufacturer": "FERRARI", "name": "512", "code": "512"},
            {"manufacturer": "FERRARI", "name": "550", "code": "550"},
            {"manufacturer": "FERRARI", "name": "575", "code": "575"},
            {"manufacturer": "FERRARI", "name": "599", "code": "599"},
            {"manufacturer": "FERRARI", "name": "612", "code": "612"},
            {"manufacturer": "FERRARI", "name": "812", "code": "812"},
            {"manufacturer": "FERRARI", "name": "California", "code": "CALIFORNIA"},
            {"manufacturer": "FERRARI", "name": "Enzo", "code": "ENZO"},
            {"manufacturer": "FERRARI", "name": "F12", "code": "F12"},
            {"manufacturer": "FERRARI", "name": "F355", "code": "F355"},
            {"manufacturer": "FERRARI", "name": "F430", "code": "F430"},
            {"manufacturer": "FERRARI", "name": "F8", "code": "F8"},
            {"manufacturer": "FERRARI", "name": "FF", "code": "FF"},
            {"manufacturer": "FERRARI", "name": "GTC4Lusso", "code": "GTC4LUSSO"},
            {"manufacturer": "FERRARI", "name": "LaFerrari", "code": "LAFERRARI"},
            {"manufacturer": "FERRARI", "name": "Portofino", "code": "PORTOFINO"},
            {"manufacturer": "FERRARI", "name": "Roma", "code": "ROMA"},
            {"manufacturer": "FERRARI", "name": "SF90", "code": "SF90"},
            {"manufacturer": "FERRARI", "name": "Testarossa", "code": "TESTAROSSA"},

            # Ford Models
            {"manufacturer": "FORD", "name": "Aerostar", "code": "AEROSTAR"},
            {"manufacturer": "FORD", "name": "Aspire", "code": "ASPIRE"},
            {"manufacturer": "FORD", "name": "Bronco", "code": "BRONCO"},
            {"manufacturer": "FORD", "name": "Bronco II", "code": "BRONCO2"},
            {"manufacturer": "FORD", "name": "C-Max", "code": "CMAX"},
            {"manufacturer": "FORD", "name": "Contour", "code": "CONTOUR"},
            {"manufacturer": "FORD", "name": "Crown Victoria", "code": "CROWNVIC"},
            {"manufacturer": "FORD", "name": "E-Series", "code": "ESERIES"},
            {"manufacturer": "FORD", "name": "EcoSport", "code": "ECOSPORT"},
            {"manufacturer": "FORD", "name": "Edge", "code": "EDGE"},
            {"manufacturer": "FORD", "name": "Escape", "code": "ESCAPE"},
            {"manufacturer": "FORD", "name": "Escort", "code": "ESCORT"},
            {"manufacturer": "FORD", "name": "Excursion", "code": "EXCURSION"},
            {"manufacturer": "FORD", "name": "Expedition", "code": "EXPEDITION"},
            {"manufacturer": "FORD", "name": "Explorer", "code": "EXPLORER"},
            {"manufacturer": "FORD", "name": "F-150", "code": "F150"},
            {"manufacturer": "FORD", "name": "F-250", "code": "F250"},
            {"manufacturer": "FORD", "name": "F-350", "code": "F350"},
            {"manufacturer": "FORD", "name": "Fairmont", "code": "FAIRMONT"},
            {"manufacturer": "FORD", "name": "Festiva", "code": "FESTIVA"},
            {"manufacturer": "FORD", "name": "Fiesta", "code": "FIESTA"},
            {"manufacturer": "FORD", "name": "Five Hundred", "code": "FIVEHUNDRED"},
            {"manufacturer": "FORD", "name": "Flex", "code": "FLEX"},
            {"manufacturer": "FORD", "name": "Focus", "code": "FOCUS"},
            {"manufacturer": "FORD", "name": "Freestar", "code": "FREESTAR"},
            {"manufacturer": "FORD", "name": "Freestyle", "code": "FREESTYLE"},
            {"manufacturer": "FORD", "name": "Fusion", "code": "FUSION"},
            {"manufacturer": "FORD", "name": "Granada", "code": "GRANADA"},
            {"manufacturer": "FORD", "name": "GT", "code": "GT"},
            {"manufacturer": "FORD", "name": "LTD", "code": "LTD"},
            {"manufacturer": "FORD", "name": "Maverick", "code": "MAVERICK"},
            {"manufacturer": "FORD", "name": "Mustang", "code": "MUSTANG"},
            {"manufacturer": "FORD", "name": "Probe", "code": "PROBE"},
            {"manufacturer": "FORD", "name": "Ranger", "code": "RANGER"},
            {"manufacturer": "FORD", "name": "Taurus", "code": "TAURUS"},
            {"manufacturer": "FORD", "name": "Tempo", "code": "TEMPO"},
            {"manufacturer": "FORD", "name": "Thunderbird", "code": "THUNDERBIRD"},
            {"manufacturer": "FORD", "name": "Transit", "code": "TRANSIT"},
            {"manufacturer": "FORD", "name": "Windstar", "code": "WINDSTAR"},

            # Genesis Models
            {"manufacturer": "GENESIS", "name": "G70", "code": "G70"},
            {"manufacturer": "GENESIS", "name": "G80", "code": "G80"},
            {"manufacturer": "GENESIS", "name": "G90", "code": "G90"},
            {"manufacturer": "GENESIS", "name": "GV70", "code": "GV70"},
            {"manufacturer": "GENESIS", "name": "GV80", "code": "GV80"},

            # GMC Models
            {"manufacturer": "GMC", "name": "Acadia", "code": "ACADIA"},
            {"manufacturer": "GMC", "name": "Canyon", "code": "CANYON"},
            {"manufacturer": "GMC", "name": "Envoy", "code": "ENVOY"},
            {"manufacturer": "GMC", "name": "Jimmy", "code": "JIMMY"},
            {"manufacturer": "GMC", "name": "Safari", "code": "SAFARI"},
            {"manufacturer": "GMC", "name": "Savana", "code": "SAVANA"},
            {"manufacturer": "GMC", "name": "Sierra", "code": "SIERRA"},
            {"manufacturer": "GMC", "name": "Sonoma", "code": "SONOMA"},
            {"manufacturer": "GMC", "name": "Suburban", "code": "SUBURBAN"},
            {"manufacturer": "GMC", "name": "Terrain", "code": "TERRAIN"},
            {"manufacturer": "GMC", "name": "Typhoon", "code": "TYPHOON"},
            {"manufacturer": "GMC", "name": "Vandura", "code": "VANDURA"},
            {"manufacturer": "GMC", "name": "Yukon", "code": "YUKON"},

           # Honda Models
            {"manufacturer": "HONDA", "name": "Accord", "code": "ACCORD"},
            {"manufacturer": "HONDA", "name": "Civic", "code": "CIVIC"},
            {"manufacturer": "HONDA", "name": "Clarity", "code": "CLARITY"},
            {"manufacturer": "HONDA", "name": "CR-V", "code": "CRV"},
            {"manufacturer": "HONDA", "name": "CR-Z", "code": "CRZ"},
            {"manufacturer": "HONDA", "name": "Crosstour", "code": "CROSSTOUR"},
            {"manufacturer": "HONDA", "name": "Del Sol", "code": "DELSOL"},
            {"manufacturer": "HONDA", "name": "Element", "code": "ELEMENT"},
            {"manufacturer": "HONDA", "name": "Fit", "code": "FIT"},
            {"manufacturer": "HONDA", "name": "HR-V", "code": "HRV"},
            {"manufacturer": "HONDA", "name": "Insight", "code": "INSIGHT"},
            {"manufacturer": "HONDA", "name": "Odyssey", "code": "ODYSSEY"},
            {"manufacturer": "HONDA", "name": "Passport", "code": "PASSPORT"},
            {"manufacturer": "HONDA", "name": "Pilot", "code": "PILOT"},
            {"manufacturer": "HONDA", "name": "Prelude", "code": "PRELUDE"},
            {"manufacturer": "HONDA", "name": "Ridgeline", "code": "RIDGELINE"},
            {"manufacturer": "HONDA", "name": "S2000", "code": "S2000"},

            # Hyundai Models
            {"manufacturer": "HYUNDAI", "name": "Accent", "code": "ACCENT"},
            {"manufacturer": "HYUNDAI", "name": "Azera", "code": "AZERA"},
            {"manufacturer": "HYUNDAI", "name": "Elantra", "code": "ELANTRA"},
            {"manufacturer": "HYUNDAI", "name": "Entourage", "code": "ENTOURAGE"},
            {"manufacturer": "HYUNDAI", "name": "Excel", "code": "EXCEL"},
            {"manufacturer": "HYUNDAI", "name": "Genesis", "code": "GENESIS"},
            {"manufacturer": "HYUNDAI", "name": "Ioniq", "code": "IONIQ"},
            {"manufacturer": "HYUNDAI", "name": "Kona", "code": "KONA"},
            {"manufacturer": "HYUNDAI", "name": "Palisade", "code": "PALISADE"},
            {"manufacturer": "HYUNDAI", "name": "Santa Fe", "code": "SANTAFE"},
            {"manufacturer": "HYUNDAI", "name": "Scoupe", "code": "SCOUPE"},
            {"manufacturer": "HYUNDAI", "name": "Sonata", "code": "SONATA"},
            {"manufacturer": "HYUNDAI", "name": "Tiburon", "code": "TIBURON"},
            {"manufacturer": "HYUNDAI", "name": "Tucson", "code": "TUCSON"},
            {"manufacturer": "HYUNDAI", "name": "Veloster", "code": "VELOSTER"},
            {"manufacturer": "HYUNDAI", "name": "Venue", "code": "VENUE"},
            {"manufacturer": "HYUNDAI", "name": "Veracruz", "code": "VERACRUZ"},
            {"manufacturer": "HYUNDAI", "name": "XG300", "code": "XG300"},
            {"manufacturer": "HYUNDAI", "name": "XG350", "code": "XG350"},

            # Infiniti Models
            {"manufacturer": "INFINITI", "name": "EX", "code": "EX"},
            {"manufacturer": "INFINITI", "name": "FX", "code": "FX"},
            {"manufacturer": "INFINITI", "name": "G", "code": "G"},
            {"manufacturer": "INFINITI", "name": "I", "code": "I"},
            {"manufacturer": "INFINITI", "name": "J", "code": "J"},
            {"manufacturer": "INFINITI", "name": "JX", "code": "JX"},
            {"manufacturer": "INFINITI", "name": "M", "code": "M"},
            {"manufacturer": "INFINITI", "name": "Q40", "code": "Q40"},
            {"manufacturer": "INFINITI", "name": "Q45", "code": "Q45"},
            {"manufacturer": "INFINITI", "name": "Q50", "code": "Q50"},
            {"manufacturer": "INFINITI", "name": "Q60", "code": "Q60"},
            {"manufacturer": "INFINITI", "name": "Q70", "code": "Q70"},
            {"manufacturer": "INFINITI", "name": "QX4", "code": "QX4"},
            {"manufacturer": "INFINITI", "name": "QX30", "code": "QX30"},
            {"manufacturer": "INFINITI", "name": "QX50", "code": "QX50"},
            {"manufacturer": "INFINITI", "name": "QX55", "code": "QX55"},
            {"manufacturer": "INFINITI", "name": "QX56", "code": "QX56"},
            {"manufacturer": "INFINITI", "name": "QX60", "code": "QX60"},
            {"manufacturer": "INFINITI", "name": "QX70", "code": "QX70"},
            {"manufacturer": "INFINITI", "name": "QX80", "code": "QX80"},

            # Jeep Models
            {"manufacturer": "JEEP", "name": "Cherokee", "code": "CHEROKEE"},
            {"manufacturer": "JEEP", "name": "Comanche", "code": "COMANCHE"},
            {"manufacturer": "JEEP", "name": "Commander", "code": "COMMANDER"},
            {"manufacturer": "JEEP", "name": "Compass", "code": "COMPASS"},
            {"manufacturer": "JEEP", "name": "Gladiator", "code": "GLADIATOR"},
            {"manufacturer": "JEEP", "name": "Grand Cherokee", "code": "GRANDCHEROKEE"},
            {"manufacturer": "JEEP", "name": "Grand Wagoneer", "code": "GRANDWAGONEER"},
            {"manufacturer": "JEEP", "name": "Liberty", "code": "LIBERTY"},
            {"manufacturer": "JEEP", "name": "Patriot", "code": "PATRIOT"},
            {"manufacturer": "JEEP", "name": "Renegade", "code": "RENEGADE"},
            {"manufacturer": "JEEP", "name": "Wagoneer", "code": "WAGONEER"},
            {"manufacturer": "JEEP", "name": "Wrangler", "code": "WRANGLER"},

            # Kia Models
            {"manufacturer": "KIA", "name": "Amanti", "code": "AMANTI"},
            {"manufacturer": "KIA", "name": "Borrego", "code": "BORREGO"},
            {"manufacturer": "KIA", "name": "Cadenza", "code": "CADENZA"},
            {"manufacturer": "KIA", "name": "Carnival", "code": "CARNIVAL"},
            {"manufacturer": "KIA", "name": "Forte", "code": "FORTE"},
            {"manufacturer": "KIA", "name": "K5", "code": "K5"},
            {"manufacturer": "KIA", "name": "K900", "code": "K900"},
            {"manufacturer": "KIA", "name": "Niro", "code": "NIRO"},
            {"manufacturer": "KIA", "name": "Optima", "code": "OPTIMA"},
            {"manufacturer": "KIA", "name": "Rio", "code": "RIO"},
            {"manufacturer": "KIA", "name": "Rondo", "code": "RONDO"},
            {"manufacturer": "KIA", "name": "Sedona", "code": "SEDONA"},
            {"manufacturer": "KIA", "name": "Seltos", "code": "SELTOS"},
            {"manufacturer": "KIA", "name": "Sephia", "code": "SEPHIA"},
            {"manufacturer": "KIA", "name": "Sorento", "code": "SORENTO"},
            {"manufacturer": "KIA", "name": "Soul", "code": "SOUL"},
            {"manufacturer": "KIA", "name": "Spectra", "code": "SPECTRA"},
            {"manufacturer": "KIA", "name": "Sportage", "code": "SPORTAGE"},
            {"manufacturer": "KIA", "name": "Stinger", "code": "STINGER"},
            {"manufacturer": "KIA", "name": "Telluride", "code": "TELLURIDE"},

            # Lamborghini Models
            {"manufacturer": "LAMBO", "name": "Aventador", "code": "AVENTADOR"},
            {"manufacturer": "LAMBO", "name": "Countach", "code": "COUNTACH"},
            {"manufacturer": "LAMBO", "name": "Diablo", "code": "DIABLO"},
            {"manufacturer": "LAMBO", "name": "Gallardo", "code": "GALLARDO"},
            {"manufacturer": "LAMBO", "name": "Huracan", "code": "HURACAN"},
            {"manufacturer": "LAMBO", "name": "Murcielago", "code": "MURCIELAGO"},
            {"manufacturer": "LAMBO", "name": "Urus", "code": "URUS"},

            # Lexus Models
            {"manufacturer": "LEXUS", "name": "CT", "code": "CT"},
            {"manufacturer": "LEXUS", "name": "ES", "code": "ES"},
            {"manufacturer": "LEXUS", "name": "GS", "code": "GS"},
            {"manufacturer": "LEXUS", "name": "GX", "code": "GX"},
            {"manufacturer": "LEXUS", "name": "HS", "code": "HS"},
            {"manufacturer": "LEXUS", "name": "IS", "code": "IS"},
            {"manufacturer": "LEXUS", "name": "LC", "code": "LC"},
            {"manufacturer": "LEXUS", "name": "LFA", "code": "LFA"},
            {"manufacturer": "LEXUS", "name": "LS", "code": "LS"},
            {"manufacturer": "LEXUS", "name": "LX", "code": "LX"},
            {"manufacturer": "LEXUS", "name": "NX", "code": "NX"},
            {"manufacturer": "LEXUS", "name": "RC", "code": "RC"},
            {"manufacturer": "LEXUS", "name": "RX", "code": "RX"},
            {"manufacturer": "LEXUS", "name": "SC", "code": "SC"},
            {"manufacturer": "LEXUS", "name": "UX", "code": "UX"},

            # Lincoln Models
            {"manufacturer": "LINCOLN", "name": "Aviator", "code": "AVIATOR"},
            {"manufacturer": "LINCOLN", "name": "Blackwood", "code": "BLACKWOOD"},
            {"manufacturer": "LINCOLN", "name": "Continental", "code": "CONTINENTAL"},
            {"manufacturer": "LINCOLN", "name": "Corsair", "code": "CORSAIR"},
            {"manufacturer": "LINCOLN", "name": "LS", "code": "LS"},
            {"manufacturer": "LINCOLN", "name": "Mark LT", "code": "MARKLT"},
            {"manufacturer": "LINCOLN", "name": "Mark VII", "code": "MARKVII"},
            {"manufacturer": "LINCOLN", "name": "Mark VIII", "code": "MARKVIII"},
            {"manufacturer": "LINCOLN", "name": "MKC", "code": "MKC"},
            {"manufacturer": "LINCOLN", "name": "MKS", "code": "MKS"},
            {"manufacturer": "LINCOLN", "name": "MKT", "code": "MKT"},
            {"manufacturer": "LINCOLN", "name": "MKX", "code": "MKX"},
            {"manufacturer": "LINCOLN", "name": "MKZ", "code": "MKZ"},
            {"manufacturer": "LINCOLN", "name": "Nautilus", "code": "NAUTILUS"},
            {"manufacturer": "LINCOLN", "name": "Navigator", "code": "NAVIGATOR"},
            {"manufacturer": "LINCOLN", "name": "Town Car", "code": "TOWNCAR"},
            {"manufacturer": "LINCOLN", "name": "Zephyr", "code": "ZEPHYR"},

            # Mazda Models
            {"manufacturer": "MAZDA", "name": "2", "code": "2"},
            {"manufacturer": "MAZDA", "name": "3", "code": "3"},
            {"manufacturer": "MAZDA", "name": "5", "code": "5"},
            {"manufacturer": "MAZDA", "name": "6", "code": "6"},
            {"manufacturer": "MAZDA", "name": "323", "code": "323"},
            {"manufacturer": "MAZDA", "name": "626", "code": "626"},
            {"manufacturer": "MAZDA", "name": "929", "code": "929"},
            {"manufacturer": "MAZDA", "name": "B-Series", "code": "BSERIES"},
            {"manufacturer": "MAZDA", "name": "CX-3", "code": "CX3"},
            {"manufacturer": "MAZDA", "name": "CX-30", "code": "CX30"},
            {"manufacturer": "MAZDA", "name": "CX-5", "code": "CX5"},
            {"manufacturer": "MAZDA", "name": "CX-7", "code": "CX7"},
            {"manufacturer": "MAZDA", "name": "CX-9", "code": "CX9"},
            {"manufacturer": "MAZDA", "name": "GLC", "code": "GLC"},
            {"manufacturer": "MAZDA", "name": "Millenia", "code": "MILLENIA"},
            {"manufacturer": "MAZDA", "name": "MPV", "code": "MPV"},
            {"manufacturer": "MAZDA", "name": "MX-3", "code": "MX3"},
            {"manufacturer": "MAZDA", "name": "MX-5 Miata", "code": "MX5MIATA"},
            {"manufacturer": "MAZDA", "name": "MX-6", "code": "MX6"},
            {"manufacturer": "MAZDA", "name": "Navajo", "code": "NAVAJO"},
            {"manufacturer": "MAZDA", "name": "Protege", "code": "PROTEGE"},
            {"manufacturer": "MAZDA", "name": "RX-7", "code": "RX7"},
            {"manufacturer": "MAZDA", "name": "RX-8", "code": "RX8"},
            {"manufacturer": "MAZDA", "name": "Tribute", "code": "TRIBUTE"},

            # Mercedes-Benz Models
            {"manufacturer": "MERC", "name": "190", "code": "190"},
            {"manufacturer": "MERC", "name": "A-Class", "code": "ACLASS"},
            {"manufacturer": "MERC", "name": "B-Class", "code": "BCLASS"},
            {"manufacturer": "MERC", "name": "C-Class", "code": "CCLASS"},
            {"manufacturer": "MERC", "name": "CL-Class", "code": "CLCLASS"},
            {"manufacturer": "MERC", "name": "CLA", "code": "CLA"},
            {"manufacturer": "MERC", "name": "CLK", "code": "CLK"},
            {"manufacturer": "MERC", "name": "CLS", "code": "CLS"},
            {"manufacturer": "MERC", "name": "E-Class", "code": "ECLASS"},
            {"manufacturer": "MERC", "name": "EQC", "code": "EQC"},
            {"manufacturer": "MERC", "name": "G-Class", "code": "GCLASS"},
            {"manufacturer": "MERC", "name": "GL-Class", "code": "GLCLASS"},
            {"manufacturer": "MERC", "name": "GLA", "code": "GLA"},
            {"manufacturer": "MERC", "name": "GLB", "code": "GLB"},
            {"manufacturer": "MERC", "name": "GLC", "code": "GLC"},
            {"manufacturer": "MERC", "name": "GLE", "code": "GLE"},
            {"manufacturer": "MERC", "name": "GLK", "code": "GLK"},
            {"manufacturer": "MERC", "name": "GLS", "code": "GLS"},
            {"manufacturer": "MERC", "name": "M-Class", "code": "MCLASS"},
            {"manufacturer": "MERC", "name": "Metris", "code": "METRIS"},
            {"manufacturer": "MERC", "name": "R-Class", "code": "RCLASS"},
            {"manufacturer": "MERC", "name": "S-Class", "code": "SCLASS"},
            {"manufacturer": "MERC", "name": "SL-Class", "code": "SLCLASS"},
            {"manufacturer": "MERC", "name": "SLC", "code": "SLC"},
            {"manufacturer": "MERC", "name": "SLK", "code": "SLK"},
            {"manufacturer": "MERC", "name": "SLR McLaren", "code": "SLRMCLAREN"},
            {"manufacturer": "MERC", "name": "SLS AMG", "code": "SLSAMG"},
            {"manufacturer": "MERC", "name": "Sprinter", "code": "SPRINTER"},

            # Mitsubishi Models
            {"manufacturer": "MITSUBISHI", "name": "3000GT", "code": "3000GT"},
            {"manufacturer": "MITSUBISHI", "name": "Diamante", "code": "DIAMANTE"},
            {"manufacturer": "MITSUBISHI", "name": "Eclipse", "code": "ECLIPSE"},
            {"manufacturer": "MITSUBISHI", "name": "Endeavor", "code": "ENDEAVOR"},
            {"manufacturer": "MITSUBISHI", "name": "Expo", "code": "EXPO"},
            {"manufacturer": "MITSUBISHI", "name": "Galant", "code": "GALANT"},
            {"manufacturer": "MITSUBISHI", "name": "i-MiEV", "code": "IMIEV"},
            {"manufacturer": "MITSUBISHI", "name": "Lancer", "code": "LANCER"},
            {"manufacturer": "MITSUBISHI", "name": "Mighty Max", "code": "MIGHTYMAX"},
            {"manufacturer": "MITSUBISHI", "name": "Mirage", "code": "MIRAGE"},
            {"manufacturer": "MITSUBISHI", "name": "Montero", "code": "MONTERO"},
            {"manufacturer": "MITSUBISHI", "name": "Outlander", "code": "OUTLANDER"},
            {"manufacturer": "MITSUBISHI", "name": "Precis", "code": "PRECIS"},
            {"manufacturer": "MITSUBISHI", "name": "Raider", "code": "RAIDER"},
            {"manufacturer": "MITSUBISHI", "name": "Sigma", "code": "SIGMA"},
            {"manufacturer": "MITSUBISHI", "name": "Starion", "code": "STARION"},

            # Nissan Models
            {"manufacturer": "NISSAN", "name": "200SX", "code": "200SX"},
            {"manufacturer": "NISSAN", "name": "240SX", "code": "240SX"},
            {"manufacturer": "NISSAN", "name": "300ZX", "code": "300ZX"},
            {"manufacturer": "NISSAN", "name": "350Z", "code": "350Z"},
            {"manufacturer": "NISSAN", "name": "370Z", "code": "370Z"},
            {"manufacturer": "NISSAN", "name": "Altima", "code": "ALTIMA"},
            {"manufacturer": "NISSAN", "name": "Armada", "code": "ARMADA"},
            {"manufacturer": "NISSAN", "name": "Cube", "code": "CUBE"},
            {"manufacturer": "NISSAN", "name": "Frontier", "code": "FRONTIER"},
            {"manufacturer": "NISSAN", "name": "GT-R", "code": "GTR"},
            {"manufacturer": "NISSAN", "name": "Juke", "code": "JUKE"},
            {"manufacturer": "NISSAN", "name": "Kicks", "code": "KICKS"},
            {"manufacturer": "NISSAN", "name": "Leaf", "code": "LEAF"},
            {"manufacturer": "NISSAN", "name": "Maxima", "code": "MAXIMA"},
            {"manufacturer": "NISSAN", "name": "Murano", "code": "MURANO"},
            {"manufacturer": "NISSAN", "name": "NV", "code": "NV"},
            {"manufacturer": "NISSAN", "name": "Pathfinder", "code": "PATHFINDER"},
            {"manufacturer": "NISSAN", "name": "Pickup", "code": "PICKUP"},
            {"manufacturer": "NISSAN", "name": "Pulsar", "code": "PULSAR"},
            {"manufacturer": "NISSAN", "name": "Quest", "code": "QUEST"},
            {"manufacturer": "NISSAN", "name": "Rogue", "code": "ROGUE"},
            {"manufacturer": "NISSAN", "name": "Sentra", "code": "SENTRA"},
            {"manufacturer": "NISSAN", "name": "Stanza", "code": "STANZA"},
            {"manufacturer": "NISSAN", "name": "Titan", "code": "TITAN"},
            {"manufacturer": "NISSAN", "name": "Versa", "code": "VERSA"},
            {"manufacturer": "NISSAN", "name": "Xterra", "code": "XTERRA"},

            # Porsche Models
            {"manufacturer": "PORSCHE", "name": "911", "code": "911"},
            {"manufacturer": "PORSCHE", "name": "918", "code": "918"},
            {"manufacturer": "PORSCHE", "name": "924", "code": "924"},
            {"manufacturer": "PORSCHE", "name": "928", "code": "928"},
            {"manufacturer": "PORSCHE", "name": "944", "code": "944"},
            {"manufacturer": "PORSCHE", "name": "968", "code": "968"},
            {"manufacturer": "PORSCHE", "name": "Boxster", "code": "BOXSTER"},
            {"manufacturer": "PORSCHE", "name": "Carrera GT", "code": "CARRERAGT"},
            {"manufacturer": "PORSCHE", "name": "Cayenne", "code": "CAYENNE"},
            {"manufacturer": "PORSCHE", "name": "Cayman", "code": "CAYMAN"},
            {"manufacturer": "PORSCHE", "name": "Macan", "code": "MACAN"},
            {"manufacturer": "PORSCHE", "name": "Panamera", "code": "PANAMERA"},
            {"manufacturer": "PORSCHE", "name": "Taycan", "code": "TAYCAN"},

            # Ram Models
            {"manufacturer": "RAM", "name": "1500", "code": "1500"},
            {"manufacturer": "RAM", "name": "2500", "code": "2500"},
            {"manufacturer": "RAM", "name": "3500", "code": "3500"},
            {"manufacturer": "RAM", "name": "ProMaster", "code": "PROMASTER"},

            # Subaru Models
            {"manufacturer": "SUBARU", "name": "Ascent", "code": "ASCENT"},
            {"manufacturer": "SUBARU", "name": "Baja", "code": "BAJA"},
            {"manufacturer": "SUBARU", "name": "BRZ", "code": "BRZ"},
            {"manufacturer": "SUBARU", "name": "Crosstrek", "code": "CROSSTREK"},
            {"manufacturer": "SUBARU", "name": "Forester", "code": "FORESTER"},
            {"manufacturer": "SUBARU", "name": "Impreza", "code": "IMPREZA"},
            {"manufacturer": "SUBARU", "name": "Justy", "code": "JUSTY"},
            {"manufacturer": "SUBARU", "name": "Legacy", "code": "LEGACY"},
            {"manufacturer": "SUBARU", "name": "Loyale", "code": "LOYALE"},
            {"manufacturer": "SUBARU", "name": "Outback", "code": "OUTBACK"},
            {"manufacturer": "SUBARU", "name": "SVX", "code": "SVX"},
            {"manufacturer": "SUBARU", "name": "Tribeca", "code": "TRIBECA"},
            {"manufacturer": "SUBARU", "name": "WRX", "code": "WRX"},
            {"manufacturer": "SUBARU", "name": "XT", "code": "XT"},

            # Tesla Models
            {"manufacturer": "TESLA", "name": "Cybertruck", "code": "CYBERTRUCK"},
            {"manufacturer": "TESLA", "name": "Model 3", "code": "MODEL3"},
            {"manufacturer": "TESLA", "name": "Model S", "code": "MODELS"},
            {"manufacturer": "TESLA", "name": "Model X", "code": "MODELX"},
            {"manufacturer": "TESLA", "name": "Model Y", "code": "MODELY"},
            {"manufacturer": "TESLA", "name": "Roadster", "code": "ROADSTER"},

            # Toyota Models
            {"manufacturer": "TOYOTA", "name": "4Runner", "code": "4RUNNER"},
            {"manufacturer": "TOYOTA", "name": "86", "code": "86"},
            {"manufacturer": "TOYOTA", "name": "Avalon", "code": "AVALON"},
            {"manufacturer": "TOYOTA", "name": "Camry", "code": "CAMRY"},
            {"manufacturer": "TOYOTA", "name": "Celica", "code": "CELICA"},
            {"manufacturer": "TOYOTA", "name": "C-HR", "code": "CHR"},
            {"manufacturer": "TOYOTA", "name": "Corolla", "code": "COROLLA"},
            {"manufacturer": "TOYOTA", "name": "Cressida", "code": "CRESSIDA"},
            {"manufacturer": "TOYOTA", "name": "Crown", "code": "CROWN"},
            {"manufacturer": "TOYOTA", "name": "Echo", "code": "ECHO"},
            {"manufacturer": "TOYOTA", "name": "FJ Cruiser", "code": "FJCRUISER"},
            {"manufacturer": "TOYOTA", "name": "GR86", "code": "GR86"},
            {"manufacturer": "TOYOTA", "name": "Highlander", "code": "HIGHLANDER"},
            {"manufacturer": "TOYOTA", "name": "Land Cruiser", "code": "LANDCRUISER"},
            {"manufacturer": "TOYOTA", "name": "Matrix", "code": "MATRIX"},
            {"manufacturer": "TOYOTA", "name": "MR2", "code": "MR2"},
            {"manufacturer": "TOYOTA", "name": "Paseo", "code": "PASEO"},
            {"manufacturer": "TOYOTA", "name": "Pickup", "code": "PICKUP"},
            {"manufacturer": "TOYOTA", "name": "Previa", "code": "PREVIA"},
            {"manufacturer": "TOYOTA", "name": "Prius", "code": "PRIUS"},
            {"manufacturer": "TOYOTA", "name": "RAV4", "code": "RAV4"},
            {"manufacturer": "TOYOTA", "name": "Sequoia", "code": "SEQUOIA"},
            {"manufacturer": "TOYOTA", "name": "Sienna", "code": "SIENNA"},
            {"manufacturer": "TOYOTA", "name": "Solara", "code": "SOLARA"},
            {"manufacturer": "TOYOTA", "name": "Starlet", "code": "STARLET"},
            {"manufacturer": "TOYOTA", "name": "Supra", "code": "SUPRA"},
            {"manufacturer": "TOYOTA", "name": "T100", "code": "T100"},
            {"manufacturer": "TOYOTA", "name": "Tacoma", "code": "TACOMA"},
            {"manufacturer": "TOYOTA", "name": "Tercel", "code": "TERCEL"},
            {"manufacturer": "TOYOTA", "name": "Tundra", "code": "TUNDRA"},
            {"manufacturer": "TOYOTA", "name": "Van", "code": "VAN"},
            {"manufacturer": "TOYOTA", "name": "Venza", "code": "VENZA"},
            {"manufacturer": "TOYOTA", "name": "Yaris", "code": "YARIS"},

            # Volkswagen Models
            {"manufacturer": "VW", "name": "Arteon", "code": "ARTEON"},
            {"manufacturer": "VW", "name": "Atlas", "code": "ATLAS"},
            {"manufacturer": "VW", "name": "Beetle", "code": "BEETLE"},
            {"manufacturer": "VW", "name": "Cabrio", "code": "CABRIO"},
            {"manufacturer": "VW", "name": "Cabriolet", "code": "CABRIOLET"},
            {"manufacturer": "VW", "name": "CC", "code": "CC"},
            {"manufacturer": "VW", "name": "Corrado", "code": "CORRADO"},
            {"manufacturer": "VW", "name": "Eos", "code": "EOS"},
            {"manufacturer": "VW", "name": "Eurovan", "code": "EUROVAN"},
            {"manufacturer": "VW", "name": "Fox", "code": "FOX"},
            {"manufacturer": "VW", "name": "GLI", "code": "GLI"},
            {"manufacturer": "VW", "name": "Golf", "code": "GOLF"},
            {"manufacturer": "VW", "name": "GTI", "code": "GTI"},
            {"manufacturer": "VW", "name": "ID.4", "code": "ID4"},
            {"manufacturer": "VW", "name": "Jetta", "code": "JETTA"},
            {"manufacturer": "VW", "name": "Passat", "code": "PASSAT"},
            {"manufacturer": "VW", "name": "Phaeton", "code": "PHAETON"},
            {"manufacturer": "VW", "name": "Quantum", "code": "QUANTUM"},
            {"manufacturer": "VW", "name": "R32", "code": "R32"},
            {"manufacturer": "VW", "name": "Rabbit", "code": "RABBIT"},
            {"manufacturer": "VW", "name": "Routan", "code": "ROUTAN"},
            {"manufacturer": "VW", "name": "Scirocco", "code": "SCIROCCO"},
            {"manufacturer": "VW", "name": "Taos", "code": "TAOS"},
            {"manufacturer": "VW", "name": "Tiguan", "code": "TIGUAN"},
            {"manufacturer": "VW", "name": "Touareg", "code": "TOUAREG"},
            {"manufacturer": "VW", "name": "Vanagon", "code": "VANAGON"},

            # Volvo Models
            {"manufacturer": "VOLVO", "name": "240", "code": "240"},
            {"manufacturer": "VOLVO", "name": "740", "code": "740"},
            {"manufacturer": "VOLVO", "name": "760", "code": "760"},
            {"manufacturer": "VOLVO", "name": "780", "code": "780"},
            {"manufacturer": "VOLVO", "name": "850", "code": "850"},
            {"manufacturer": "VOLVO", "name": "940", "code": "940"},
            {"manufacturer": "VOLVO", "name": "960", "code": "960"},
            {"manufacturer": "VOLVO", "name": "C30", "code": "C30"},
            {"manufacturer": "VOLVO", "name": "C40", "code": "C40"},
            {"manufacturer": "VOLVO", "name": "C70", "code": "C70"},
            {"manufacturer": "VOLVO", "name": "S40", "code": "S40"},
            {"manufacturer": "VOLVO", "name": "S60", "code": "S60"},
            {"manufacturer": "VOLVO", "name": "S70", "code": "S70"},
            {"manufacturer": "VOLVO", "name": "S80", "code": "S80"},
            {"manufacturer": "VOLVO", "name": "S90", "code": "S90"},
            {"manufacturer": "VOLVO", "name": "V40", "code": "V40"},
            {"manufacturer": "VOLVO", "name": "V50", "code": "V50"},
            {"manufacturer": "VOLVO", "name": "V60", "code": "V60"},
            {"manufacturer": "VOLVO", "name": "V70", "code": "V70"},
            {"manufacturer": "VOLVO", "name": "V90", "code": "V90"},
            {"manufacturer": "VOLVO", "name": "XC40", "code": "XC40"},
            {"manufacturer": "VOLVO", "name": "XC60", "code": "XC60"},
            {"manufacturer": "VOLVO", "name": "XC70", "code": "XC70"},
            {"manufacturer": "VOLVO", "name": "XC90", "code": "XC90"},
  ]
  
        for model_data in models_data:
            mfg = manufacturers[model_data["manufacturer"]]
            model, created = VehicleModel.objects.get_or_create(
                manufacturer=mfg,
                code=model_data["code"],
                defaults={"name": model_data["name"]},
            )
            if created:
                self.stdout.write(f"  Created model: {mfg.name} {model.name}")

        # Create Part Categories
        parts_data = [
                {"name": "Engine", "description": "Complete engine assembly or engine block"},
                {"name": "Transmission", "description": "Complete transmission assembly including gearbox"},
                {"name": "Alternator", "description": "Electrical generator for charging battery"},
                {"name": "Axle Assembly", "description": "Complete axle with differential housing"},
                {"name": "AC Compressor", "description": "Air conditioning compressor unit"},
                {"name": "Fuel Pump", "description": "Electric or mechanical fuel delivery pump"},
                {"name": "Brake Booster", "description": "Vacuum or hydraulic brake assist unit"},
                {"name": "Steering Column", "description": "Steering shaft and column assembly"},
                {"name": "Wheel Rim", "description": "Metal wheel rim or alloy wheel"},
                {"name": "Bumper", "description": "Front or rear bumper cover"},
                {"name": "Headlight", "description": "Front headlight assembly"},
                {"name": "Taillight", "description": "Rear taillight assembly"},
                {"name": "Door", "description": "Complete door assembly or door shell"},
                {"name": "Hood", "description": "Front hood or bonnet panel"},
                {"name": "Fender", "description": "Front or rear fender panel"},
                {"name": "Side View Mirror", "description": "External side mirror assembly"},
                {"name": "Dashboard", "description": "Instrument panel or dashboard assembly"},
                {"name": "Seat", "description": "Front or rear seat assembly"},
                {"name": "Sunroof", "description": "Sunroof or moonroof assembly"},
                {"name": "Heater Core", "description": "Interior heating radiator core"},
                {"name": "Grille", "description": "Front grille or grill assembly"},
                {"name": "Flywheel", "description": "Engine flywheel or flexplate"},
                {"name": "Oil Pan", "description": "Engine oil pan or sump"},
                {"name": "Transfer Case", "description": "4WD/AWD transfer case assembly"},
                {"name": "Turbocharger", "description": "Turbo charger or supercharger unit"},
                {"name": "Power Steering Pump", "description": "Hydraulic power steering pump"},
                {"name": "Shock Absorber", "description": "Hydraulic shock absorber"},
                {"name": "Strut", "description": "MacPherson strut assembly"},
                {"name": "Control Arm", "description": "Suspension control arm or A-arm"},
                {"name": "Ball Joint", "description": "Suspension ball joint"},
                {"name": "Brake Caliper", "description": "Disc brake caliper assembly"},
                {"name": "Driveshaft", "description": "Propeller shaft or drive shaft"},
                {"name": "Air Filter", "description": "Engine air filter or air cleaner"},
                {"name": "Exhaust Manifold", "description": "Exhaust manifold or header"},
                {"name": "Intake Manifold", "description": "Engine intake manifold"},
                {"name": "Window Regulator", "description": "Power or manual window mechanism"},
                {"name": "Windshield", "description": "Front windshield glass"},
                {"name": "Fuel Injector", "description": "Fuel injection nozzle"},
                {"name": "Ignition Coil", "description": "Spark ignition coil pack"},
                {"name": "Speedometer Cluster", "description": "Instrument cluster with gauges"},
                {"name": "Wiring Harness", "description": "Electrical wiring loom or harness"},
                {"name": "ECU Computer", "description": "Engine control unit or computer module"},
                {"name": "Door Lock Actuator", "description": "Power door lock motor"},
                {"name": "Fuel Tank", "description": "Gasoline or diesel fuel tank"},
                {"name": "Steering Rack", "description": "Rack and pinion steering gear"},
                {"name": "Differential", "description": "Rear or front differential assembly"},
                {"name": "Hub Assembly", "description": "Wheel hub and bearing assembly"},
                {"name": "Spindle", "description": "Wheel spindle or stub axle"},
                {"name": "Knuckle", "description": "Steering knuckle or upright"},
                {"name": "Suspension Arm", "description": "Upper or lower suspension arm"},
                {"name": "Spring", "description": "Coil spring or leaf spring"},
                {"name": "Trunk Lid", "description": "Rear trunk or boot lid"},
                {"name": "Spoiler", "description": "Rear spoiler or wing"},
                {"name": "Crossmember", "description": "Frame crossmember or subframe"},
                {"name": "Mount Bracket", "description": "Engine or component mounting bracket"},
                {"name": "Engine Cradle", "description": "Engine subframe or cradle"},
                {"name": "Control Module", "description": "Electronic control module"},
                {"name": "Valve Cover", "description": "Engine valve cover or rocker cover"},
                {"name": "Oil Pump", "description": "Engine oil circulation pump"},
                {"name": "Fuel Rail", "description": "Fuel injection rail"},
                {"name": "Airbag", "description": "Driver or passenger airbag module"},
                {"name": "Seat Belt", "description": "Seat belt assembly with retractor"},
                {"name": "Sensor", "description": "Various electronic sensors"},
                {"name": "Oxygen Sensor", "description": "O2 sensor or lambda sensor"},
                {"name": "Mass Air Flow Sensor", "description": "MAF sensor for air intake"},
                {"name": "ABS Module", "description": "Anti-lock brake system module"},
                {"name": "Radiator Fan", "description": "Electric cooling fan assembly"},
                {"name": "Blower Motor", "description": "HVAC blower motor fan"},
                {"name": "HVAC Control", "description": "Climate control unit"},
                {"name": "Radio", "description": "Car radio or stereo head unit"},
                {"name": "Infotainment Unit", "description": "Touch screen infotainment system"},
                {"name": "Antenna", "description": "Radio or GPS antenna"},
                {"name": "GPS Module", "description": "Navigation GPS receiver"},
                {"name": "Camera", "description": "Backup or surround view camera"},
                {"name": "Rearview Mirror", "description": "Interior rearview mirror"},
                {"name": "Door Handle", "description": "Interior or exterior door handle"},
                {"name": "Tailgate", "description": "Rear tailgate or liftgate"},
                {"name": "Cargo Door", "description": "Rear cargo or barn door"},
                {"name": "Side Step", "description": "Running board or side step"},
                {"name": "Roof Rack", "description": "Luggage roof rack system"},
                {"name": "Fuel Door", "description": "Fuel filler door or gas cap"},
                {"name": "License Plate Bracket", "description": "License plate mounting bracket"},
                {"name": "Fog Light", "description": "Front or rear fog lamp"},
                {"name": "Signal Light", "description": "Turn signal light assembly"},
                {"name": "Backup Light", "description": "Reverse light assembly"},
                {"name": "Headlamp Switch", "description": "Headlight control switch"},
                {"name": "Turn Signal Switch", "description": "Turn signal stalk or switch"},
                {"name": "Wiper Motor", "description": "Windshield wiper motor"},
                {"name": "Washer Pump", "description": "Windshield washer fluid pump"},
                {"name": "Coolant Reservoir", "description": "Coolant overflow tank"},
                {"name": "Overflow Tank", "description": "Expansion or overflow reservoir"},
                {"name": "Brake Line", "description": "Brake fluid line or hose"},
                {"name": "Clutch Master Cylinder", "description": "Clutch hydraulic master cylinder"},
                {"name": "Slave Cylinder", "description": "Clutch hydraulic slave cylinder"},
                {"name": "Shifter", "description": "Gear shifter or shift lever"},
                {"name": "Gearbox", "description": "Manual or automatic gearbox"},
                {"name": "Torque Converter", "description": "Automatic transmission torque converter"},
                {"name": "Bell Housing", "description": "Transmission bell housing"},
                {"name": "Drum", "description": "Brake drum assembly"},
                {"name": "Clutch Disc", "description": "Clutch friction disc or plate"},
                {"name": "Pedal Assembly", "description": "Brake, clutch, or accelerator pedals"},
                {"name": "Hood Latch", "description": "Hood release latch mechanism"},
                {"name": "Hinge", "description": "Door or hood hinge"},
                {"name": "Rear Panel", "description": "Rear body panel or quarter panel"},
                {"name": "Floor Pan", "description": "Floor panel or chassis floor"},
                {"name": "Radiator Support", "description": "Front radiator core support"},
                {"name": "Bumper Reinforcement", "description": "Bumper impact bar or reinforcement"},
                {"name": "Fog Lamp Bezel", "description": "Fog light trim bezel"},
                {"name": "Trim Molding", "description": "Exterior or interior trim molding"},
                {"name": "Interior Trim", "description": "Interior trim panels"},
                {"name": "Dash Bezel", "description": "Dashboard trim bezel"},
                {"name": "Cup Holder", "description": "Cup holder or drink holder"},
                {"name": "Glove Box", "description": "Glove compartment or glove box"},
                {"name": "Console", "description": "Center console assembly"},
                {"name": "Armrest", "description": "Seat or door armrest"},
                {"name": "Seat Cover", "description": "Seat upholstery or cover"},
                {"name": "Door Panel", "description": "Interior door trim panel"},
                {"name": "Rear Deck", "description": "Rear deck or parcel shelf"},
                {"name": "Tail Panel", "description": "Rear tail panel or valance"},
                {"name": "Rear Bumper", "description": "Rear bumper cover assembly"},
                {"name": "Front Bumper", "description": "Front bumper cover assembly"},
                {"name": "Door Mirror", "description": "Side door mirror assembly"},
                {"name": "Engine Cover", "description": "Decorative engine cover"},
                {"name": "Valve Body", "description": "Automatic transmission valve body"},
                {"name": "Oil Cooler", "description": "Engine or transmission oil cooler"},
                {"name": "Transmission Cooler", "description": "Transmission fluid cooler"},
                {"name": "Clutch Cable", "description": "Mechanical clutch cable"},
                {"name": "Accelerator Pedal", "description": "Gas pedal or throttle pedal"},
                {"name": "Brake Pedal", "description": "Brake pedal assembly"},
                {"name": "Seat Frame or Track", "description": "Seat mounting frame or slider track"},
                {"name": "Rear Axle", "description": "Rear axle shaft or assembly"},
                {"name": "Front Axle", "description": "Front axle shaft or assembly"},
                {"name": "Drivetrain", "description": "Complete drivetrain system"},
                {"name": "Motor Controller", "description": "Electric motor controller (EV/Hybrid)"},
                {"name": "Drive Unit", "description": "Electric drive unit assembly (EV/Hybrid)"},
                {"name": "Thermostat", "description": "Coolant thermostat valve"},
                {"name": "Radiator Cap", "description": "Pressure radiator cap"},
                {"name": "Fan Shroud", "description": "Radiator fan shroud"},
                {"name": "Air Duct", "description": "Air intake or cooling duct"},
                {"name": "Engine Mount", "description": "Engine mounting bracket or cushion"},
                {"name": "Transmission Mount", "description": "Transmission mounting bracket"},
                {"name": "Floor Shift Assembly", "description": "Floor mounted shifter assembly"},
                {"name": "Center Console", "description": "Center console with storage"},
                {"name": "Rear Defroster", "description": "Rear window defroster grid"},
                {"name": "Blower Resistor", "description": "HVAC blower motor resistor"},
    ]

        for part_data in parts_data:
            part, created = PartCategory.objects.get_or_create(
                name=part_data["name"],
                defaults={"description": part_data["description"]},
            )
            if created:
                self.stdout.write(f"  Created part category: {part.name}")

        self.stdout.write(self.style.SUCCESS("Successfully populated sample data!"))
